# Generated by Django 5.2.2 on 2025-06-09 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Esperado (Sistema)')),
                ('counted_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Contado')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diferencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cerró')),
            ],
        ),
    ]
