# Generated by Django 5.2.2 on 2025-06-12 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cashcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Método')),
                ('adjustment_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: -10.00 para 10% de descuento, 8.50 para 8.5% de recargo.', max_digits=5, verbose_name='Ajuste porcentual (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final (con ajuste)'),
        ),
        migrations.AlterField(
            model_name='cashcount',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Esperado'),
        ),
        migrations.AlterField(
            model_name='cashcount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (sin ajuste)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.paymentmethod', verbose_name='Método de Pago'),
        ),
    ]
