# Generated by Django 5.2.2 on 2025-06-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paymentmethod_sale_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Completada', max_length=20, verbose_name='Estado'),
        ),
    ]
