# Generated by Django 5.2.2 on 2025-06-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_person',
            field=models.CharField(default=0, max_length=100, verbose_name='Persona de Contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
